### Importar librerias

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

### Cargar datos

In [ ]:
df = pd.read_csv("Creatividad_Digital\datos\campanas_creatividad_digital.csv")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Laboratorio\AppData\Local\Temp\ipykernel_5380\67225622.py:1: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv("Creatividad_Digital\datos\campanas_creatividad_digital.csv")

In [18]:
df

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,impresiones,alcance,clicks,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa
0,CAMP-0001,2025-01-02,LumaAds,YouTube,Reel,30,Traffic,MX,2449.27,2356.84,319655,212076,4073,171648,26034,82,626.92,79
1,CAMP-0002,2025-01-03,FrameHouse,Facebook,Reel,25,Traffic,AR,1153.08,836.40,185919,103138,3718,88732,22749,93,678.65,93
2,CAMP-0003,2025-01-04,PixelForge,Facebook,Video Largo,60,Ventas,PE,398.93,291.12,50288,27514,488,22772,9557,24,1082.33,63
3,CAMP-0004,2025-01-05,FrameHouse,YouTube,Video Largo,90,Awareness,AR,1752.35,1304.59,279213,210519,2491,177098,29152,19,64.42,69
4,CAMP-0005,2025-01-06,NeoStudio,Instagram,Video Largo,45,Ventas,CL,703.80,640.98,140856,109020,1878,68165,39455,137,5787.29,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,CAMP-0176,2025-06-26,LumaAds,YouTube,Carrusel,0,Traffic,CL,1580.90,1038.68,208212,162608,2364,46551,14449,73,526.98,88
176,CAMP-0177,2025-06-27,LumaAds,Facebook,Imagen,0,Traffic,AR,1942.07,1686.23,343280,179363,5831,87296,25884,167,1424.52,78
177,CAMP-0178,2025-06-28,CromaLab,YouTube,Imagen,0,Traffic,AR,2561.05,2464.58,383086,218732,5467,95338,36307,163,1392.68,85
178,CAMP-0179,2025-06-29,CromaLab,Instagram,Story,15,Traffic,CO,2109.14,1511.14,364814,217284,8112,250048,108926,247,2059.09,92
179,CAMP-0180,2025-06-30,CromaLab,Facebook,Carrusel,0,Leads,MX,3216.03,3156.29,746485,554270,10367,193659,47865,466,10702.31,80

In [17]:
pd.reset_option("display.max_row")

In [13]:
df.columns

Index(['id_campana', 'fecha', 'cliente', 'plataforma', 'formato',
       'duracion_seg', 'objetivo', 'pais', 'presupuesto_usd', 'costo_usd',
       'impresiones', 'alcance', 'clicks', 'reproducciones_3s',
       'reproducciones_100', 'conversiones', 'ingresos_usd',
       'calificacion_creativa'],
      dtype='str')

In [19]:
df.shape

(180, 18)

In [20]:
df.dtypes

id_campana                   str
fecha                        str
cliente                      str
plataforma                   str
formato                      str
duracion_seg               int64
objetivo                     str
pais                         str
presupuesto_usd          float64
costo_usd                float64
impresiones                int64
alcance                    int64
clicks                     int64
reproducciones_3s          int64
reproducciones_100         int64
conversiones               int64
ingresos_usd             float64
calificacion_creativa      int64
dtype: object

In [22]:
df.isna().sum()

id_campana               0
fecha                    0
cliente                  0
plataforma               0
formato                  0
duracion_seg             0
objetivo                 0
pais                     0
presupuesto_usd          0
costo_usd                0
impresiones              0
alcance                  0
clicks                   0
reproducciones_3s        0
reproducciones_100       0
conversiones             0
ingresos_usd             0
calificacion_creativa    0
dtype: int64

In [ ]:
#Indicadores basicos
df['ctr'] = df['clicks'] / df['impresiones'] #Tasa de clicks
df['cvr'] = df['conversiones'] / df['clicks'] #Tasa de conversion

#Indicadores de costo
df['cpc'] = df['costo_usd'] / df['clicks'] #Costo por click
df['cpm'] = (df['costo_usd'] / df['impresiones']) * 1000 #Costo por miles

#Indicador compuesto
df['roi'] = (df['ingresos_usd'] - df['costo_usd']) / df['costo_usd'] #Retorno sobre inversion

In [26]:
df.head()

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
0,CAMP-0001,2025-01-02,LumaAds,YouTube,Reel,30,Traffic,MX,2449.27,2356.84,...,171648,26034,82,626.92,79,0.012742,0.020133,0.578650,7.373074,-0.734000
1,CAMP-0002,2025-01-03,FrameHouse,Facebook,Reel,25,Traffic,AR,1153.08,836.40,...,88732,22749,93,678.65,93,0.019998,0.025013,0.224960,4.498733,-0.188606
2,CAMP-0003,2025-01-04,PixelForge,Facebook,Video Largo,60,Ventas,PE,398.93,291.12,...,22772,9557,24,1082.33,63,0.009704,0.049180,0.596557,5.789055,2.717814
3,CAMP-0004,2025-01-05,FrameHouse,YouTube,Video Largo,90,Awareness,AR,1752.35,1304.59,...,177098,29152,19,64.42,69,0.008922,0.007627,0.523721,4.672383,-0.950621
4,CAMP-0005,2025-01-06,NeoStudio,Instagram,Video Largo,45,Ventas,CL,703.80,640.98,...,68165,39455,137,5787.29,73,0.013333,0.072950,0.341310,4.550605,8.028815

In [27]:
df[['roi','costo_usd']]

          roi  costo_usd
0   -0.734000    2356.84
1   -0.188606     836.40
2    2.717814     291.12
3   -0.950621    1304.59
4    8.028815     640.98
..        ...        ...
175 -0.492645    1038.68
176 -0.155204    1686.23
177 -0.434922    2464.58
178  0.362607    1511.14
179  2.390788    3156.29

[180 rows x 2 columns]

In [37]:
mediana = df.costo_usd.median()
df[(df.costo_usd > mediana) & (df.roi < 0)]

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
0,CAMP-0001,2025-01-02,LumaAds,YouTube,Reel,30,Traffic,MX,2449.27,2356.84,...,171648,26034,82,626.92,79,0.012742,0.020133,0.578650,7.373074,-0.734000
6,CAMP-0007,2025-01-08,PixelForge,X,Imagen,0,Traffic,AR,3216.04,3070.29,...,101883,29422,74,661.87,70,0.010021,0.017540,0.727729,7.292798,-0.784428
9,CAMP-0010,2025-01-11,CromaLab,Instagram,Reel,25,Traffic,AR,1921.01,1435.89,...,172708,42644,143,1181.10,62,0.020407,0.022851,0.229449,4.682413,-0.177444
13,CAMP-0014,2025-01-15,FrameHouse,YouTube,Reel,25,Awareness,PE,2386.46,2023.31,...,142472,28150,41,132.93,71,0.016858,0.007652,0.377624,6.366174,-0.934301
14,CAMP-0015,2025-01-16,NeoStudio,X,Reel,10,Awareness,AR,3112.81,2981.28,...,245674,141110,66,214.46,74,0.015961,0.009700,0.438166,6.993697,-0.928064
17,CAMP-0018,2025-01-19,CromaLab,YouTube,Carrusel,0,Traffic,CO,2069.62,1978.87,...,63143,23991,110,835.63,64,0.014833,0.017147,0.308475,4.575538,-0.577724
21,CAMP-0022,2025-01-23,NeoStudio,Instagram,Carrusel,0,Traffic,PE,2681.44,1906.26,...,65374,24516,161,1377.99,71,0.019582,0.019321,0.228760,4.479657,-0.277124
29,CAMP-0030,2025-01-31,CromaLab,Instagram,Story,5,Awareness,CL,3330.21,2706.67,...,311841,150378,143,405.77,88,0.022318,0.012653,0.239486,5.344851,-0.850085
32,CAMP-0033,2025-02-03,CromaLab,Instagram,Story,5,Leads,PE,3015.60,4734.53,...,238701,62434,101,2917.99,75,0.006133,0.042048,1.971078,12.087935,-0.383679
40,CAMP-0041,2025-02-11,CromaLab,Facebook,Reel,25,Traffic,PE,3490.07,2800.99,...,298841,55591,219,1655.69,69,0.017177,0.020000,0.255798,4.393896,-0.408891
43,CAMP-0044,2025-02-14,LumaAds,YouTube,Story,10,Traffic,PE,1784.71,1445.39,...,81637,13936,83,741.26,77,0.015817,0.025744,0.448322,7.091015,-0.487156
46,CAMP-0047,2025-02-17,PixelForge,TikTok,Imagen,0,Traffic,CL,3018.24,2862.26,...,219737,89066,346,2519.02,71,0.015970,0.023811,0.196976,3.145783,-0.119919
51,CAMP-0052,2025-02-22,PixelForge,TikTok,Story,15,Awareness,CO,2806.17,2684.83,...,456966,253818,119,418.00,83,0.022063,0.008123,0.183265,4.043388,-0.844310
58,CAMP-0059,2025-03-01,PixelForge,Facebook,Story,10,Awareness,PE,3172.62,2419.88,...,234566,72152,63,201.71,74,0.017822,0.009246,0.355134,6.329081,-0.916645
60,CAMP-0061,2025-03-03,NeoStudio,Facebook,Story,10,Awareness,CO,2075.47,1835.76,...,234491,38136,94,276.51,100,0.025152,0.010979,0.214408,5.392886,-0.849376
61,CAMP-0062,2025-03-04,LumaAds,YouTube,Reel,30,Awareness,AR,2997.46,2333.96,...,329709,164890,111,356.91,86,0.020349,0.011756,0.247189,5.030097,-0.847080
78,CAMP-0079,2025-03-21,LumaAds,X,Reel,10,Traffic,PE,2050.99,1613.43,...,86898,42314,42,334.84,47,0.012950,0.013287,0.510418,6.610007,-0.792467
83,CAMP-0084,2025-03-26,CromaLab,YouTube,Imagen,0,Traffic,CO,2730.02,2322.90,...,56802,20305,117,973.19,83,0.013323,0.021358,0.424042,5.649584,-0.581045
88,CAMP-0089,2025-03-31,LumaAds,TikTok,Imagen,0,Awareness,CL,3332.78,3065.68,...,89118,36640,138,435.84,79,0.019528,0.009900,0.219920,4.294692,-0.857833
90,CAMP-0091,2025-04-02,PixelForge,Instagram,Reel,30,Awareness,MX,2249.98,1658.00,...,198781,94574,73,227.65,74,0.018749,0.009122,0.207172,3.884359,-0.862696
93,CAMP-0094,2025-04-05,FrameHouse,TikTok,Reel,30,Awareness,PE,2569.17,2392.89,...,447548,125382,167,506.02,83,0.032378,0.008005,0.114701,3.713822,-0.788532
101,CAMP-0102,2025-04-13,NeoStudio,TikTok,Imagen,0,Traffic,CO,1855.22,1815.33,...,83937,21875,154,1197.55,73,0.015148,0.017683,0.208443,3.157551,-0.340313
107,CAMP-0108,2025-04-19,NeoStudio,YouTube,Carrusel,0,Traffic,CO,2373.99,1832.05,...,41111,4161,98,710.59,79,0.014196,0.026133,0.488547,6.935433,-0.612134
109,CAMP-0110,2025-04-21,LumaAds,Instagram,Imagen,0,Awareness,MX,1887.66,1418.09,...,81247,17243,36,106.33,64,0.012256,0.008229,0.324135,3.972619,-0.925019
118,CAMP-0119,2025-04-30,LumaAds,Instagram,Reel,25,Awareness,PE,2799.22,2373.88,...,260841,136151,73,251.52,66,0.019347,0.006194,0.201432,3.897203,-0.894047
130,CAMP-0131,2025-05-12,PixelForge,YouTube,Story,10,Awareness,AR,2174.66,1709.48,...,123363,22793,53,181.92,72,0.016243,0.009870,0.318339,5.170825,-0.893582
135,CAMP-0136,2025-05-17,NeoStudio,Facebook,Reel,30,Traffic,CO,3052.15,2076.82,...,301328,133554,140,1278.02,59,0.018309,0.015807,0.234483,4.293274,-0.384626
137,CAMP-0138,2025-05-19,CromaLab,Instagram,Story,15,Awareness,CL,2991.56,2355.69,...,154843,75814,68,227.52,74,0.020083,0.008264,0.286302,5.749750,-0.903417
144,CAMP-0145,2025-05-26,CromaLab,Instagram,Imagen,0,Awareness,PE,1507.22,1422.27,...,81487,10230,29,92.61,71,0.012032,0.008222,0.403252,4.851796,-0.934886
154,CAMP-0155,2025-06-05,NeoStudio,YouTube,Imagen,0,Traffic,CL,2915.29,2072.34,...,60645,8227,148,1328.76,85,0.012951,0.025469,0.356624,4.618491,-0.358812
160,CAMP-0161,2025-06-11,CromaLab,Instagram,Video Largo,90,Awareness,PE,2245.94,2093.79,...,153344,31434,61,200.81,68,0.015217,0.009726,0.333831,5.079820,-0.904093
165,CAMP-0166,2025-06-16,LumaAds,X,Imagen,0,Traffic,CO,3452.15,3323.14,...,107430,12756,167,1326.26,83,0.011443,0.025740,0.512198,5.860927,-0.600902
167,CAMP-0168,2025-06-18,FrameHouse,Instagram,Video Largo,90,Awareness,CO,3127.85,2437.50,...,228910,38255,56,186.59,77,0.014069,0.007814,0.340100,4.784994,-0.923450
169,CAMP-0170,2025-06-20,FrameHouse,X,Carrusel,0,Awareness,AR,1625.97,1619.30,...,38757,16230,36,124.84,83,0.013186,0.011360,0.510981,6.737651,-0.922905
176,CAMP-0177,2025-06-27,LumaAds,Facebook,Imagen,0,Traffic,AR,1942.07,1686.23,...,87296,25884,167,1424.52,78,0.016986,0.028640,0.289184,4.912113,-0.155204
177,CAMP-0178,2025-06-28,CromaLab,YouTube,Imagen,0,Traffic,AR,2561.05,2464.58,...,95338,36307,163,1392.68,85,0.014271,0.029815,0.450810,6.433490,-0.434922

In [28]:
df[df.costo_usd > df.costo_usd.median()]

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
0,CAMP-0001,2025-01-02,LumaAds,YouTube,Reel,30,Traffic,MX,2449.27,2356.84,...,171648,26034,82,626.92,79,0.012742,0.020133,0.578650,7.373074,-0.734000
6,CAMP-0007,2025-01-08,PixelForge,X,Imagen,0,Traffic,AR,3216.04,3070.29,...,101883,29422,74,661.87,70,0.010021,0.017540,0.727729,7.292798,-0.784428
9,CAMP-0010,2025-01-11,CromaLab,Instagram,Reel,25,Traffic,AR,1921.01,1435.89,...,172708,42644,143,1181.10,62,0.020407,0.022851,0.229449,4.682413,-0.177444
11,CAMP-0012,2025-01-13,FrameHouse,Facebook,Imagen,0,Ventas,CL,3008.26,2130.48,...,74370,33084,168,7365.38,51,0.009963,0.040956,0.519376,5.174660,2.457146
12,CAMP-0013,2025-01-14,FrameHouse,Instagram,Story,5,Ventas,CO,2680.92,1796.24,...,285090,49961,448,19192.94,66,0.020648,0.053691,0.215273,4.444994,9.685064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,CAMP-0175,2025-06-25,NeoStudio,TikTok,Imagen,0,Leads,CO,1699.84,1676.35,...,71115,27792,445,8235.26,77,0.017088,0.059097,0.222623,3.804232,3.912614
176,CAMP-0177,2025-06-27,LumaAds,Facebook,Imagen,0,Traffic,AR,1942.07,1686.23,...,87296,25884,167,1424.52,78,0.016986,0.028640,0.289184,4.912113,-0.155204
177,CAMP-0178,2025-06-28,CromaLab,YouTube,Imagen,0,Traffic,AR,2561.05,2464.58,...,95338,36307,163,1392.68,85,0.014271,0.029815,0.450810,6.433490,-0.434922
178,CAMP-0179,2025-06-29,CromaLab,Instagram,Story,15,Traffic,CO,2109.14,1511.14,...,250048,108926,247,2059.09,92,0.022236,0.030449,0.186285,4.142220,0.362607
179,CAMP-0180,2025-06-30,CromaLab,Facebook,Carrusel,0,Leads,MX,3216.03,3156.29,...,193659,47865,466,10702.31,80,0.013888,0.044950,0.304455,4.228203,2.390788

In [38]:
df.plataforma.unique()

<StringArray>
['YouTube', 'Facebook', 'Instagram', 'X', 'TikTok']
Length: 5, dtype: str

In [40]:
df[(df['plataforma'] == "TikTok") | (df['plataforma'] == "Instagram")].sort_values('roi', ascending=False)[:10]

,id_campana,fecha,cliente,plataforma,formato,duracion_seg,objetivo,pais,presupuesto_usd,costo_usd,...,reproducciones_3s,reproducciones_100,conversiones,ingresos_usd,calificacion_creativa,ctr,cvr,cpc,cpm,roi
150,CAMP-0151,2025-06-01,PixelForge,TikTok,Story,5,Ventas,AR,1446.89,1432.64,...,311799,64308,944,49322.31,76,0.026206,0.074460,0.113002,2.961358,33.427567
54,CAMP-0055,2025-02-25,PixelForge,TikTok,Story,10,Ventas,AR,2158.86,1952.28,...,437914,115208,1222,60119.39,72,0.026451,0.073579,0.117551,3.109320,29.794451
158,CAMP-0159,2025-06-09,NeoStudio,TikTok,Reel,10,Ventas,CO,3472.48,2900.57,...,524059,134825,1656,84100.28,77,0.031839,0.058857,0.103091,3.282365,27.994398
100,CAMP-0101,2025-04-12,PixelForge,TikTok,Carrusel,0,Ventas,AR,3117.30,2218.04,...,195432,85354,1198,62497.38,82,0.021383,0.077360,0.143229,3.062715,27.176850
66,CAMP-0067,2025-03-09,NeoStudio,TikTok,Reel,15,Ventas,CO,2782.13,1882.76,...,258009,144902,962,46784.54,76,0.021614,0.082788,0.162028,3.502001,23.848913
19,CAMP-0020,2025-01-21,CromaLab,TikTok,Reel,10,Ventas,MX,1098.95,937.63,...,201724,66975,420,22218.58,62,0.023523,0.056734,0.126655,2.979318,22.696533
157,CAMP-0158,2025-06-08,NeoStudio,TikTok,Video Largo,90,Ventas,MX,1059.73,1057.54,...,152145,73612,441,19772.16,84,0.017460,0.087569,0.209996,3.666463,17.696371
31,CAMP-0032,2025-02-02,LumaAds,TikTok,Story,10,Ventas,CL,1744.15,1227.09,...,186500,89677,465,21556.20,70,0.023939,0.071892,0.189717,4.541599,16.566927
138,CAMP-0139,2025-05-20,LumaAds,TikTok,Reel,20,Ventas,MX,1739.96,1535.43,...,192421,44875,601,26374.02,75,0.025734,0.061774,0.157820,4.061318,16.176960
22,CAMP-0023,2025-01-24,FrameHouse,TikTok,Imagen,0,Ventas,CO,1925.22,1677.89,...,63564,10786,706,28810.28,79,0.021216,0.081637,0.194021,4.116380,16.170542